/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef plugin_CONSTANTS_H
#define plugin_CONSTANTS_H

#include "plugin_types.h"

namespace apache { namespace thrift { namespace plugin {

class pluginConstants {
 public:
  pluginConstants();

};

extern const pluginConstants g_plugin_constants;

}}} // namespace

#endif
