/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "plugin_constants.h"

namespace apache { namespace thrift { namespace plugin {

const pluginConstants g_plugin_constants;

pluginConstants::pluginConstants() {
}

}}} // namespace

